OBJS=lesson02.o
BIN=lesson02.bin

include ../Makefile.include

#lesson02.o : lesson02.c
#	$(CC) $(CFLAGS) $(INCLUDES) -g -c lesson02.c -o lesson02.o -Wno-deprecated-declarations
#
#lesson02.bin: $(OBJS)
#	$(CC) -o lesson02.bin -Wl,--whole-archive $(LDFLAGS) $(OBJS) -Wl,--no-whole-archive -rdynamic



